server:
  port: 8086
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: “黑马商城商品服务服务接口文档"
    package: com.hmall.pay.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  #sentinel控制台地址
      http-method-specify: true # 开启请求方式前缀
  rabbitmq:
    host: 157.245.206.115
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123